from typing import Protocol

from src.objects import Food, Snake


class Renderer(Protocol):
    def draw_snake(self, snake: Snake) -> None: ...
    def draw_food(self, food: Food) -> None: ...
    def draw_scene(self, snakes: list[Snake], food: Food) -> None: ...
    def quit(self) -> None: ...
